### ISSUE TITLE
Support for AWS Secrets Manager

### ISSUE THREAD

**Issue by MelodicsVincent** [nshgraph/gpt_helper#1]
Hi @nshgraph! Thanks for running an insightful chat at Melodics last week alongside Alyona.

I'm looking at integrating GPTHelper with Melodics' Slack workspace, however we don't use AWS Systems Manager. I'd like to raise a pull request to read secrets from AWS Secrets Manager at some point.

Cheers,
Vincent (Melodics)

**Comment by MelodicsVincent** [comment]
closing as I'll make the changes on a fork

**Comment by nshgraph** [comment]
Cheers! A fork might be better and I know this repo is highly opinionated on the things we happened to use already. 

Keen to hear how you get on though... the logic should be the same.
