### ISSUE TITLE
"role": "user" is assigned to bot messages

### ISSUE THREAD

**Issue by MelodicsVincent** [nshgraph/gpt_helper#2]
`"role": "user"` is currently assigned to all messages. 

It looks like this should be fixed such that `"role": "assistant"` is used to desginate bot messages

**Comment by nshgraph** [comment]
https://github.com/nshgraph/gpt_helper/blob/main/app.py#L54 this _should_ mean that bot messages are marked using assistant. Are you seeing them marked as user?

We definitely did have this issue originally and having the bot talk to itself thinking it was all user content was entertaining. The fact that it kept mentioning itself and started conversing without user input was slightly disturbing though.

**Comment by MelodicsVincent** [comment]
Yes I am seeing all reponses marked as "user". When I logged the value of `data` it showed that "role": "user" is used for bot responses.

I believe the `actor` variable is calculated correctly but not actually being used elsewhere in the file? 

`thread_messages.append(("user", message))` appends hardcoded string `"user"` regardless of the user. (https://github.com/nshgraph/gpt_helper/blob/main/app.py#L59)

**Comment by nshgraph** [comment]
Thanks. Very true.

**Comment by nshgraph** [comment]
This should be fixed in https://github.com/nshgraph/gpt_helper/pull/3
